### PR TITLE
Fix warning on files in /etc/mdevctl.d/scripts.d/

### LINKED ISSUE #52: WARN when script below script.d directly
I observed the following behavior.

1. Create a script `/etc/mdevctl.d/scripts.d/exit0.sh`
2. Have the script run bash to `exit 0`
3. Run:
```bash
# mdevctl define -t <valid_type> --parent <valid_parent>
cbfa3222-3db3-49f0-a031-52c5f8ecb2e3
# mdevctl start -u cbfa3222-3db3-49f0-a031-52c5f8ecb2e3
```
Result:
```bash
[2021-11-30T14:56:07Z WARN  mdevctl] Can't determine uuid for file 'exit0.sh'
```

I was a bit surprised. I used `script.d` as my "script repository" during script development for testing, that is, create and edit them there before moving them finally to the subfolders.

The action is still executed. But I discussed with @jonner that it could make sense to investigate this.

### PR DESCRIPTION
**Pull request by jonner**
Fixes #52

### CODE REVIEW

**Comment by cohuck** [comment]
Changes look good to me.

File: src/tests.rs [hunk 1]
```diff
@@ -49,9 +49,8 @@ impl TestEnvironment {
         fs::create_dir_all(test.mdev_base()).expect("Unable to create mdev_base");
         fs::create_dir_all(test.persist_base()).expect("Unable to create persist_base");
         fs::create_dir_all(test.parent_base()).expect("Unable to create parent_base");
-        fs::create_dir_all(test.callout_script_base())
-            .expect("Unable to create callout_script_base");
-        fs::create_dir_all(test.callout_notification_base())
+        fs::create_dir_all(test.callout_dir()).expect("Unable to create callout_script_base");
```
Comment (jonner) [inline src/tests.rs:52]: Oops, I forgot to update the name in the error message here and below
